runtime: python39

entrypoint: gunicorn -b :$PORT server:app

env_variables:
  PROJECT_ID: "code-institute-433215"
  LOCATION: "us-central1"
  ENDPOINT_ID: "1150104555816484864"


handlers:
- url: /static
  static_dir: hackathon/static

- url: /.*
  script: auto

