runtime: python39

entrypoint: gunicorn -b :$PORT server:app

env_variables:
  PROJECT_ID: "marine-copilot-433717-q0"
  LOCATION: "europe-west3"
  ENDPOINT_ID: "6442984207139471360"


handlers:
- url: /static
  static_dir: hackathon/static

- url: /.*
  script: auto

