runtime: python39

entrypoint: gunicorn -b :$PORT server:app

env_variables:
  PROJECT_ID: "code-institute-433215"
  LOCATION: "europe-west2"
  ENDPOINT_ID: "2189985269971681280"


handlers:
- url: /static
  static_dir: hackathon/static

- url: /.*
  script: auto

